// Ergast API service for historical F1 data
// Now using local JSON files generated by scripts/fetch_historical_data.py

const ERGAST_BASE_URL = 'https://ergast.com/api/f1';

export interface ErgastDriver {
    driverId: string;
    givenName: string;
    familyName: string;
    nationality: string;
}

export interface ErgastConstructor {
    constructorId: string;
    name: string;
    nationality: string;
}

// Interfaces for the raw Ergast format (kept for reference or type safety if needed)
export interface ErgastRace {
    season: string;
    round: string;
    raceName: string;
    Circuit: {
        circuitId: string;
        circuitName: string;
        Location: {
            locality: string;
            country: string;
        };
    };
    date: string;
    Results?: Array<{
        position: string;
        Driver: ErgastDriver;
        Constructor: ErgastConstructor;
        Time?: { time: string };
        status: string;
        points: string;
    }>;
}

export interface ErgastStanding {
    position: string;
    points: string;
    wins: string;
    Driver?: ErgastDriver;
    Constructor?: ErgastConstructor;
    Constructors?: ErgastConstructor[];
}

export interface SeasonData {
    year: number;
    driverChampion: {
        name: string;
        team: string;
        points: number;
    };
    constructorChampion: {
        name: string;
        points: number;
    };
    races: Array<{
        round: number;
        name: string;
        circuit: string;
        country: string;
        date: string;
        winner: string;
        team: string;
    }>;
    driverStandings: Array<{
        position: number;
        driver: string;
        team: string;
        points: number;
        wins: number;
    }>;
    constructorStandings: Array<{
        position: number;
        constructor: string;
        points: number;
        wins: number;
    }>;
}

/**
 * Fetch complete season data from local storage
 * Data is pre-fetched by python scripts and stored in /public/data/seasons/
 */
export const fetchSeasonData = async (year: number): Promise<SeasonData> => {
    try {
        // Use local JSON files generated by the python script
        // import.meta.env.BASE_URL handles the deployment path (e.g. /StratX/)
        const response = await fetch(`${import.meta.env.BASE_URL}data/seasons/${year}.json`);

        if (!response.ok) {
            throw new Error(`Season data not found for ${year}`);
        }

        // The JSON file is already in the exact SeasonData format
        return await response.json();
    } catch (error) {
        console.error(`Error fetching season data for ${year}:`, error);
        throw error;
    }
};

/**
 * Fetch race results for a specific race from local storage
 * Data is pre-fetched by python scripts and stored in /public/data/races/
 */
export const fetchRaceResults = async (year: number, round: number) => {
    try {
        const response = await fetch(`${import.meta.env.BASE_URL}data/races/${year}/${round}.json`);

        if (!response.ok) {
            // Fallback: Return null if detailed race data isn't available yet
            console.warn(`Race detail data not found for ${year} round ${round}`);
            return null;
        }

        return await response.json();
    } catch (error) {
        console.error(`Error fetching race results for ${year} round ${round}:`, error);
        throw error;
    }
};
